import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/header/Header";
import prisma from "@/lib/prisma";
import { SnippetsProvider } from "@/contexts/SnippetsContext";

import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	const { userId, redirectToSignIn } = await auth();
	// if (!userId) return <div>Pas connecté</div>;
	if (!userId) return redirectToSignIn();

	const snippets = await prisma.snippet.findMany({
		include: {
			category: true,
			language: true,
		},
	});

	const categories = await prisma.category.findMany();
	const languages = await prisma.language.findMany();

	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<SnippetsProvider
						initialSnippets={snippets}
						initialCategories={categories}
						initialLanguages={languages}
					>
						<Header />

						<main>{children}</main>
					</SnippetsProvider>
					<Toaster />
				</body>
			</html>
		</ClerkProvider>
	);
}
